DATASET:
  NAME: "pancreas_tumors"
  TRAIN_PATH: "./data/pancreas_tumors/train"
  VAL_PATH: "./data/pancreas_tumors/val"
  TEST_PATH: "./data/pancreas_tumors/test"
  IMAGE_FORMAT: ".tif"
  MASK_FORMAT: ".tif"
  NUM_SHOTS: 100
  TYPE: "binary"
  IGNORE_BG: False

SAM:
  MODEL: "vit_b" # [vit_h, vit_l, vit_b, default]
  CHECKPOINT: "segment_anything/checkpoints"
  RANK: 4

TRAIN:
  BATCH_SIZE: 4
  NUM_EPOCHS: 1
  LEARNING_RATE: 0.002

TEST:
  USE_LATEST: False

PROMPT_LEARNER:
  MODEL: "biomedclip"
  MODALITY: "text"
  CTX_INIT: "an ultrasound scan of"
  N_CTX_TEXT: 4
  N_CTX_VISION: 4
  PROMPT_DEPTH_VISION: 12
  PROMPT_DEPTH_TEXT: 12
  CSC: True
  CLASS_TOKEN_POSITION: "end"
  BACKBONE: "ViT-B/16"
  CLASSNAMES: ["background","pancreas tumor"]
